### ISSUE TITLE
Python 3.9 Support

### ISSUE THREAD

**Issue by nathanielatom** [flexxui/pscript#50]
In Python 3.9.1

`from pscript import py2js`

results in 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.9/site-packages/pscript/__init__.py", line 272, in <module>
    from .parser0 import Parser0, JSError
  File ".../lib/python3.9/site-packages/pscript/parser0.py", line 19, in <module>
    from . import commonast as ast
  File ".../lib/python3.9/site-packages/pscript/commonast.py", line 15, in <module>
    from base64 import encodestring as encodebytes, decodestring as decodebytes
ImportError: cannot import name 'encodestring' from 'base64' (.../lib/python3.9/base64.py)
```

**Comment by ese942** [comment]
base64.encodestring has been [deprecated since python3.1](https://docs.python.org/3.8/library/base64.html#base64.encodestring).  It still existed in python 3.8, seems it was removed in 3.9.  Damn python devs don't understand that minor version increments don't introduce breaking changes...

The quick and dirty fix is to define it in your code before invoking pscript:
```
import base64
base64.encodestring = base64.encodebytes
base64.decodestring = base64.decodebytes
from pscript import py2js
```

That should be it.  The docs say encodestring is an alias of encodebytes, and my quick test indicates they return the same type (a bytes object rather than a string).  If the return value were different then you might need to transform it between the two, but that  doesn't seem to be the case.

Note: I have no affiliation with pscript.  Just answering on my python knowledge.  If pscript is still being maintained, the devs may want to fix this so the above mitigation is no longer necessary.

Hope this helps.

**Comment by almarklein** [comment]
> python devs don't understand that minor version increments don't introduce breaking changes...

I don't think that Python uses semver versioning. Python *does* occasionally break backwards compatibility in dot-releases.

> the devs may want to fix this so the above mitigation is no longer necessary.

Good point. I'll add a CI build for py39 and make sure it works again. There may be other problems, since the ast spec can also be changed between Python versions.

**Comment by almarklein** [comment]
done! will release in a minute

**Comment by garvanwalshe** [comment]
It seems to have come back with 3.9.2. when following the guide on readthedocs.  I tried the [quick and dirty fix](https://github.com/flexxui/pscript/issues/50#issuecomment-750875154) and that worked but should flag that it's not completely fixed. (Flexx looks great btw!) 


`from flexx import flx`

gives

```
Traceback (most recent call last):
  File ".../introflex.py", line 1, in <module>
    from flexx import flx
  File ".../lib/python3.9/site-packages/flexx/flx.py", line 10, in <module>
    from .app import *
  File ".../python3.9/site-packages/flexx/app/__init__.py", line 38, in <module>
    from ._app import App, manager
  File ".../site-packages/flexx/app/_app.py", line 11, in <module>
    from base64 import encodestring as encodebytes
ImportError: cannot import name 'encodestring' from 'base64' (/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/base64.py)
```
